Layout/LineLength:
  Max: 120
Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Style/AndOr:
  EnforcedStyle: conditionals
Style/Documentation:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
